### ISSUE TITLE
Error - Provided Metric Key is not available, tried to select; Overall Application Performance|Average Response Time (ms)

### ISSUE THREAD

**Issue by smarigowda** [codecentric/Jenkins-AppDynamics-Plugin#2] opened 2014-08-04 13:46 UTC
I am getting the following error ( i added few debugging statements to get the actual exception)

Could you please help me understand the root cause of this issue?

Message at Jenkins Console:

Started by user anonymous
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/workspace/AppDynamicsTest
[AppDynamicsTest] $ /bin/sh -xe /tmp/hudson4821710230936081104.sh
 ls -lrt
total 0
Verify connection to AppDynamics REST interface ...
Connection successful, continue to fetch measurements from AppDynamics Controller ...
Ready building AppDynamics report
Verifying for improving or degrading performance, main metric: Overall Application Performance|Average Response Time (ms) where lower is better = true
Unable to fetch (threshold) metric to determine if build is degrading. Aborting
exception is: 
java.lang.IllegalArgumentException: Provided Metric Key is not available, tried to select; Overall Application Performance|Average Response Time (ms)
this.thresholdMetric:
Overall Application Performance|Average Response Time (ms)
Build step 'AppDynamics Performance Publisher' changed build result to FAILURE
Finished: FAILURE

**Comment by StephenGoodall** [comment] 2015-04-27 11:01
Hi Miel,
Not sure if this is till active or not so apologies for tagging on to this but I'm getting the same issue as above, the Test REST Connection works but then when I run a build I get the "Unable to fetch (threshold) metric to determine if build is degrading. Aborting" error.

I do get XML returned if I add in the application name to the URL you provided above:

![2015-04-27_1157](https://cloud.githubusercontent.com/assets/5859975/7346297/e3d7a34e-ecd4-11e4-946e-71b344a1ee22.png)

Is there anything you could suggest to get round this? Could it be due to a space in the Application Name?
Thanks

**Comment by StephenGoodall** [comment] 2015-04-27 14:49
Found this in the Jenkins log, wasn't sure if it would help with this, seems to be reading the JSON response at this point?

Apr 27, 2015 1:00:33 PM nl.codecentric.jenkins.appd.rest.RestConnection fetchMetricData INFO: Some problem fetching metrics from the AppDynamics REST interface, see stack-trace for more information org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "metricId" (Class nl.codecentric.jenkins.appd.rest.types.MetricData), not marked as ignorable
at [Source: java.io.StringReader@4be9c005; line: 3, column: 22] (through reference chain: nl.codecentric.jenkins.appd.rest.types.MetricData["metricId"])
at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53)
at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:267)
at org.codehaus.jackson.map.deser.std.StdDeserializer.reportUnknownProperty(StdDeserializer.java:649)
at org.codehaus.jackson.map.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:635)
at org.codehaus.jackson.map.deser.BeanDeserializer.handleUnknownProperty(BeanDeserializer.java:1355)
at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:717)
at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:194)
at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2723)
at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1861)
at nl.codecentric.jenkins.appd.rest.RestConnection.fetchMetricData(RestConnection.java:113)
at nl.codecentric.jenkins.appd.rest.RestConnection.fetchMetricData(RestConnection.java:83)
at nl.codecentric.jenkins.appd.AppDynamicsDataCollector.createReportFromMeasurements(AppDynamicsDataCollector.java:56)
at nl.codecentric.jenkins.appd.AppDynamicsResultsPublisher.perform(AppDynamicsResultsPublisher.java:219)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1030)
at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
at hudson.model.Run.execute(Run.java:1784)
at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:519)
at hudson.model.ResourceController.execute(ResourceController.java:89)
at hudson.model.Executor.run(Executor.java:240)

**Comment by mdonkers** [comment] 2015-04-29 06:08
Thanks for the stack-trace, I'll try to look into this this week and get back with an answer or fix.

**Comment by StephenGoodall** [comment] 2015-04-29 08:38
Thanks Miel, that would be great!
I had a quick look and I think it might be something that has changed with the response AppDynamics give, perhaps it changed when they have upgraded something.

**Comment by mdonkers** [comment] 2015-04-29 19:33
Hi,

Issue should be fixed. AppDynamics added more fields to the output and Jackson (JSON) parser wouldn't just skip over them but threw the exception. Added the fields and also added a parameter to ignore unknown fields (to be future safe). I was still testing with an older AppDynamics setup so couldn't reproduce the issue, stacktrace helped enormously here ;-)

Please see version 1.0.7 of the plugin and let me know if you have more issues.

Cheers, Miel

**Closed by mdonkers** 2015-04-29 19:33 UTC

**Comment by StephenGoodall** [comment] 2015-04-29 19:41
Thanks so much Miel! I'll give it a try now :)

**Comment by StephenGoodall** [comment] 2015-04-29 20:17
Seems to be working now, thanks again :+1:
